name: Récupérer Team IDs (ligues.yaml)

on:
  workflow_dispatch:
    inputs:
      season:
        description: "Saison (ex: 2025)"
        required: true
        default: "2025"
  push:
    paths:
      - ligues.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      - name: Récupérer Team IDs
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: api-football-v1.p.rapidapi.com
        run: |
          python scripts/recuperer_team_ids.py \
            --saison "${{ github.event.inputs.season || '2025' }}" \
            --entree ligues.yaml \
            --sortie donnees/team_ids.json

      - name: Upload du fichier (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: team_ids
          path: donnees/team_ids.json
